<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class File extends Model
{
    use SoftDeletes;

    protected $fillable = [
      'title', 'overview', 'overview_short', 'price', 'live', 'approved', 'finished'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function($file){
            $file->identifier = uniqid(true);
        });
    }

//    identifikasi route model binding
    public function getRouteKeyName()
    {
        return 'identifier';
    }

    public function user()
    {
        $this->belongsTo(User::class);
    }
}
